# Generated by Django 6.1 on 2026-09-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.CharField(choices=[('design', 'UI/UX and Visual Design'), ('programming', 'Programming and Development'), ('multimedia_production', 'Multimedia Production'), ('digital_productivity', 'Digital Productivity'), ('other', 'Others')], default='others', max_length=50),
        ),
        migrations.AddField(
            model_name='skills',
            name='type',
            field=models.CharField(choices=[('soft', 'Soft Skills'), ('hard', 'Hard Skills')], default='hard', max_length=10),
        ),
    ]
